/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifierRouteImport } from './routes/verifier'
import { Route as OfficierRouteImport } from './routes/officier'
import { Route as CitoyenRouteImport } from './routes/citoyen'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMonEspaceRouteImport } from './routes/_authenticated/mon-espace'

const VerifierRoute = VerifierRouteImport.update({
  id: '/verifier',
  path: '/verifier',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficierRoute = OfficierRouteImport.update({
  id: '/officier',
  path: '/officier',
  getParentRoute: () => rootRouteImport,
} as any)
const CitoyenRoute = CitoyenRouteImport.update({
  id: '/citoyen',
  path: '/citoyen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMonEspaceRoute = AuthenticatedMonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/citoyen': typeof CitoyenRoute
  '/officier': typeof OfficierRoute
  '/verifier': typeof VerifierRoute
  '/mon-espace': typeof AuthenticatedMonEspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/citoyen': typeof CitoyenRoute
  '/officier': typeof OfficierRoute
  '/verifier': typeof VerifierRoute
  '/mon-espace': typeof AuthenticatedMonEspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/citoyen': typeof CitoyenRoute
  '/officier': typeof OfficierRoute
  '/verifier': typeof VerifierRoute
  '/_authenticated/mon-espace': typeof AuthenticatedMonEspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/auth'
    | '/citoyen'
    | '/officier'
    | '/verifier'
    | '/mon-espace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/auth'
    | '/citoyen'
    | '/officier'
    | '/verifier'
    | '/mon-espace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agent'
    | '/auth'
    | '/citoyen'
    | '/officier'
    | '/verifier'
    | '/_authenticated/mon-espace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  CitoyenRoute: typeof CitoyenRoute
  OfficierRoute: typeof OfficierRoute
  VerifierRoute: typeof VerifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verifier': {
      id: '/verifier'
      path: '/verifier'
      fullPath: '/verifier'
      preLoaderRoute: typeof VerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officier': {
      id: '/officier'
      path: '/officier'
      fullPath: '/officier'
      preLoaderRoute: typeof OfficierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citoyen': {
      id: '/citoyen'
      path: '/citoyen'
      fullPath: '/citoyen'
      preLoaderRoute: typeof CitoyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mon-espace': {
      id: '/_authenticated/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof AuthenticatedMonEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMonEspaceRoute: typeof AuthenticatedMonEspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMonEspaceRoute: AuthenticatedMonEspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  CitoyenRoute: CitoyenRoute,
  OfficierRoute: OfficierRoute,
  VerifierRoute: VerifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
